### ISSUE TITLE
Setup.exe does not support Proxy Auth

### ISSUE THREAD

**Issue by Gill-Bates** [microsoft/idfix#41]
The Setup.exe is not able to authenticate against Proxy. Setup will stop with ERROR 407.

![image](https://user-images.githubusercontent.com/25774289/101488732-47d95080-3960-11eb-8022-26adc4ec6726.png)

**Comment by AdeTF** [comment]
As a school, we also use a proxy and the setup fails. Is there anyway of downloading the exe without needing to use the online setup?

ERROR DETAILS
	Following errors were detected during this operation.
	* [23/06/2021 10:19:39] System.Deployment.Application.InvalidDeploymentException (AppFileLocationValidation)
		- HTTP redirect is not allowed for application files and assemblies. Cannot download IdFix.exe.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.ProcessDownloadedFile(Object sender, DownloadEventArgs e)
			at System.Deployment.Application.FileDownloader.DownloadModifiedEventHandler.Invoke(Object sender, DownloadEventArgs e)
			at System.Deployment.Application.FileDownloader.OnModified()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

**Comment by trevevs** [comment]
dont use the single launch setup.exe..  download the full zip package run direct from ..\idfix-master\publish\Application Files\IdFix_2_3_0_0\idfx.exe

**Comment by AdeTF** [comment]
Many thanks for the advice, works well.

**Comment by bryan-phillips-ms** [comment]
An MSI is available for install to those that cannot run the ClickOnce application:  https://github.com/microsoft/idfix/tree/master/MSIs
